name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: ['authenticator/**', 'crypto/**', 'crypto-js/**', 'Cargo.lock']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: cargo fmt --all --check -q
    - name: Run tests
      run: cargo test --verbose
